---
# For configuration options and examples, see:
# https://gethomepage.dev/configs/services/

- Multimedia:
    - Plex:
        icon: plex.png
        href: https://app.plex.tv/desktop/#!/
        ping: https://192.168.0.237:32400
        description: Serveur multimédia Plex
        widget:
            type: plex
            url: https://192.168.0.237:32400
            key: ***REMOVED***
    - Tautulli:
        icon: tautulli.png
        href: https://tautulli.battistella.ovh/
        ping: https://tautulli.battistella.ovh/
        description: Suivi des statistiques Plex Media Server
    - Seerr:
        icon: overseerr.png
        href: https://seerr.battistella.ovh/
        ping: https://seerr.battistella.ovh/
        description: Gestion des demandes de contenu multimédia
        widget:
          type: overseerr
          url: https://seerr.battistella.ovh
          key: ***REMOVED***
    - Sonarr:
        icon: sonarr.png
        href: https://sonarr.battistella.ovh/
        ping: https://sonarr.battistella.ovh/
        description: Gestion des séries télévisées
        widget:
          type: sonarr
          url: https://sonarr.battistella.ovh
          key: ***REMOVED***
    - Radarr:
        icon: radarr.png
        href: https://radarr.battistella.ovh/
        ping: https://radarr.battistella.ovh/
        description: Gestion des films
        widget:
          type: radarr
          url: https://radarr.battistella.ovh
          key: ***REMOVED***
    - Lidarr:
        icon: lidarr.png
        href: https://lidarr.battistella.ovh/
        ping: https://lidarr.battistella.ovh/
        description: Gestion de la musique
        widget:
          type: lidarr
          url: https://lidarr.battistella.ovh
          key: ***REMOVED***
    - Bazarr:
        icon: bazarr.png
        href: https://bazarr.battistella.ovh/
        ping: https://bazarr.battistella.ovh/
        description: Gestion des sous-titres
        widget:
            type: bazarr
            url: https://bazarr.battistella.ovh
            key: ***REMOVED***
    - Prowlarr:
        icon: prowlarr.png
        href: https://indexer.battistella.ovh/
        ping: https://indexer.battistella.ovh/
        description: Gestion des indexeurs
        widget:
            type: prowlarr
            url: https://indexer.battistella.ovh
            key: ***REMOVED***
    - qBittorrent:
        icon: qbittorrent.png
        href: https://qbittorrent.battistella.ovh/
        ping: https://qbittorrent.battistella.ovh/
        description: Client BitTorrent alternatif
        widget:
            type: qbittorrent
            url: https://qbittorrent.battistella.ovh
            username: admin
            password: "***REMOVED***"
- Infrastructure:
    - Dozzle:
        icon: dozzle.png
        href: https://dozzle.battistella.ovh/
        ping: https://dozzle.battistella.ovh/
        description: Visualisation des logs Docker
    - Infisical:
        icon: infisical.png
        href: https://infisical.battistella.ovh
        ping: https://infisical.battistella.ovh
        description: Gestionnaire de secrets
    - Netdata:
        icon: netdata.png
        href: https://netdata.battistella.ovh/
        ping: https://netdata.battistella.ovh/
        description: Surveillance système en temps réel
        widget:
            type: netdata
            url: https://netdata.battistella.ovh
    - Pi-hole:
        icon: pi-hole.png
        href: https://pihole.battistella.ovh/admin/
        ping: https://pihole.battistella.ovh/
        description: Bloqueur de publicités DNS
    - Portainer:
        icon: portainer.png
        href: https://portainer.battistella.ovh/
        ping: https://portainer.battistella.ovh/
        description: Gestion de conteneurs Docker
        widget:
            type: portainer
            url: https://portainer.battistella.ovh
            env: 2
            key: ***REMOVED***
    - Traefik:
        icon: traefik.png
        href: https://proxy.battistella.ovh/
        ping: https://proxy.battistella.ovh/
        description: Reverse proxy et équilibreur de charge
        widget:
            type: traefik
            url: https://proxy.battistella.ovh
    - Unifi Network:
        icon: unifi.png
        href: https://192.168.0.237:8443
        ping: https://192.168.0.237:8443
        description: Contrôleur réseau UniFi
    - Unraid:
        icon: unraid.png
        href: http://gjallarhorn.local/
        description: Système d'exploitation serveur
    - Proxmox:
        icon: proxmox.png
        href: https://192.168.0.2:8006
        description: Hypervisior
- Personnel:
    - Gramps Web:
        icon: gramps.png
        href: https://gramps.battistella.ovh/
        ping: https://gramps.battistella.ovh/
        description: Logiciel de généalogie
    - Home Assistant:
        icon: home-assistant.png
        href: https://home-assistant.battistella.ovh/
        ping: https://home-assistant.battistella.ovh/
        description: Domotique et automatisation de la maison
    - Immich:
        icon: immich.png
        href: https://immich.battistella.ovh/
        ping: https://immich.battistella.ovh/
        description: Gestionnaire de photos auto-hébergé
        widget:
            type: immich
            url: https://immich.battistella.ovh
            key: ***REMOVED***
            version: 2 # optional, default is 1
    - Techney:
        icon: docusaurus.png
        href: https://techney.battistella.ovh/
        ping: https://techney.battistella.ovh/
        description: Documentation personnelle
    - Vaultwarden:
        icon: vaultwarden.png
        href: https://vaultwarden.battistella.ovh/
        ping: https://vaultwarden.battistella.ovh/
        description: Gestionnaire de mots de passe
    - Resume:
        icon: mdi-file-account
        href: https://cv.battistella.ovh/
        ping: https://cv.battistella.ovh/
        description: CV personnel
    - The Box:
        icon: mdi-package-variant
        href: https://the-box.battistella.ovh/
        ping: https://the-box.battistella.ovh/
        description: Service The Box
    - Personal Blog:
        icon: mdi-blogger
        href: https://blog.battistella.ovh/
        ping: https://blog.battistella.ovh/
        description: Blog personnel
    - Copro Pilot:
        icon: mdi-home-city
        href: https://copro-pilot.battistella.ovh/
        ping: https://copro-pilot.battistella.ovh/
        description: Gestion de copropriété

- Utilitaires:
    - Memos:
        icon: memos.png
        href: https://memos.battistella.ovh/
        ping: https://memos.battistella.ovh/
        description: Application de notes rapides
    - Paperless-ngx:
        icon: paperless-ngx.png
        href: https://paperless.battistella.ovh/
        ping: https://paperless.battistella.ovh/
        description: Système de gestion documentaire
    - Stirling-PDF:
        icon: stirling-pdf.png
        href: https://stirling.battistella.ovh/
        ping: https://stirling.battistella.ovh/
        description: Outils de manipulation PDF
    - Wakapi:
        icon: wakapi.png
        href: https://wakapi.battistella.ovh/
        ping: https://wakapi.battistella.ovh/
        description: Suivi du temps de codage
